"""makr 애플리케이션의 상수 정의.

매직 넘버를 명명된 상수로 관리합니다.
"""

from __future__ import annotations

# DevLogic 패킷 파싱
DEVLOGIC_SEGMENT_LENGTH = 25

# F4 자동화 기본 설정
F4_DEFAULT_REPEAT_COUNT = 10
F4_DEFAULT_INTERVAL_SEC = 0.2

# 채널 감시 기본 설정 (밀리초)
DEFAULT_CHANNEL_WATCH_INTERVAL_MS = 20
DEFAULT_CHANNEL_TIMEOUT_MS = 700

# 패킷 캡처 포트
PACKET_CAPTURE_PORT = 32800

# 딜레이 기본값 (밀리초)
DEFAULT_F2_BEFORE_ESC_MS = 0
DEFAULT_F2_BEFORE_POS1_MS = 55
DEFAULT_F2_BEFORE_POS2_MS = 55
DEFAULT_F1_BEFORE_POS3_MS = 15
DEFAULT_F1_BEFORE_ENTER_MS = 15
DEFAULT_F1_REPEAT_COUNT = 8
DEFAULT_F1_NEWLINE_BEFORE_POS4_MS = 170
DEFAULT_F1_NEWLINE_BEFORE_POS3_MS = 30
DEFAULT_F1_NEWLINE_BEFORE_ENTER_MS = 15
DEFAULT_F4_BETWEEN_POS11_POS12_MS = 25
DEFAULT_F4_BEFORE_ENTER_MS = 55
DEFAULT_F5_INTERVAL_MS = 25
DEFAULT_F6_INTERVAL_MS = 25

# pos3 모드 범위
POS3_MODE_MIN = 1
POS3_MODE_MAX = 6
